# Generated by Django 3.2.9 on 2023-10-19 10:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categorys",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                ("ongoing", models.BooleanField(default=False)),
                ("company", models.CharField(max_length=200)),
                ("company_logo", models.ImageField(upload_to="cv/logo/")),
                ("job", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yer", models.DateField()),
                ("school", models.CharField(max_length=200)),
                ("diploma", models.CharField(max_length=250)),
                (
                    "learned",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=250),
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
            },
        ),
        migrations.CreateModel(
            name="Personnal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=255)),
                ("technologies", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("cv", models.FileField(upload_to="cv/personal/")),
                ("linkedin", models.URLField()),
                ("github", models.URLField()),
                ("gitlab", models.URLField()),
                ("youtube", models.URLField()),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("calendly", models.URLField()),
            ],
            options={
                "verbose_name": "Personnal",
                "verbose_name_plural": "Personnals",
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("logo", models.FileField(upload_to="cv/techno/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "task",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), size=None
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.experience"
                    ),
                ),
                ("technologies", models.ManyToManyField(to="api.Technology")),
            ],
            options={
                "verbose_name": "Company Work",
                "verbose_name_plural": "Company Works",
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="cv/projet/")),
                ("presentation", models.ImageField(upload_to="cv/projet/")),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("gitlab", models.URLField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("technologies", models.ManyToManyField(to="api.Technology")),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
            },
        ),
    ]
