# Generated by Django 3.2.6 on 2023-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
    ]
