# Generated by Django 3.2.6 on 2023-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_technology_is_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="cv/techno/"),
        ),
    ]
