# Generated by Django 3.2.6 on 2023-10-26 11:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_technology_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projet",
            old_name="presentation",
            new_name="banner",
        ),
        migrations.AddField(
            model_name="projet",
            name="feature_img",
            field=models.ImageField(blank=True, null=True, upload_to="cv/projet/"),
        ),
        migrations.AddField(
            model_name="projet",
            name="feature_video",
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="formation",
            name="learned",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250), size=None
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="task",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=250), size=None
            ),
        ),
    ]
