# Generated by Django 3.2.6 on 2023-10-26 11:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_auto_20231026_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
