# Generated by Django 4.2.6 on 2024-06-28 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_projet_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formation",
            old_name="yer",
            new_name="year",
        ),
    ]
